### ISSUE TITLE
terraform forces new resource after network rename

### ISSUE THREAD

**Issue by avaika** [terraform-providers/terraform-provider-openstack#380]
Hi,

Not sure if it's a provider issue, but will start from here.
terraform playbook forces a new compute instance in case there was a network rename operation before. Network itself keeps the same uuid and all the parameters, just a new name.

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2
- openstack_networking_network_v2

### Terraform Configuration Files
```hcl
resource "openstack_networking_network_v2" "this" {
  name           = "${var.project}_${var.environment}"
  admin_state_up = "true"
}

resource "openstack_compute_instance_v2" "this" {
  name            = "${var.domain}"
  image_name      = "${var.image}"
  flavor_name     = "${var.flavor}"
  key_pair        = "${var.key_name}"
  security_groups = ["${var.sec_groups}"]
  availability_zone = "DP1"
  network {
    uuid = "${openstack_networking_network_v2.this.id}"
  }
  #lifecycle {
  #  ignore_changes = ["network"]
  #}
}
```

### Expected Behavior
In case openstack_networking_network_v2.this.name was changed via `terraform apply`, there should be no new changes suggested by terraform in the next run.

### Actual Behavior
Terraform forces openstack_compute_instance_v2.this recreation, unless commented lifecycle is active. Like this:

```
-/+ module.ins-alfa.openstack_compute_instance_v2.this (new resource required)                    
      id:                            "fb82817d-4949-4536-9f27-65725741b5fb" => <computed> (forces new resource)
      <..>
      network.#:                     "0" => "1" (forces new resource)
      network.0.access_network:      "" => "false"
      network.0.fixed_ip_v4:         "" => <computed>
      network.0.fixed_ip_v6:         "" => <computed>
      network.0.floating_ip:         "" => <computed>
      network.0.mac:                 "" => <computed>
      network.0.name:                "" => <computed>
      network.0.port:                "" => <computed>
      network.0.uuid:                "" => "e8160f83-f286-4c1a-896e-aebd905126d0" (forces new resource)                
      region:                        "RegionOne" => <computed>
      security_groups.#:             "4" => "4"
      <..>
      stop_before_destroy:           "false" => "false"    
```

Even though in state file already network.# is 1:
```
                "openstack_compute_instance_v2.this": {
                    "type": "openstack_compute_instance_v2",
                    "depends_on": [],
                    "primary": {
                        "id": "fb82817d-4949-4536-9f27-65725741b5fb",
                        "attributes": {
                            <..>
                            "network.#": "1",
                            "network.0.access_network": "false",
                            "network.0.fixed_ip_v4": "10.0.0.6",
                            "network.0.fixed_ip_v6": "",
                            "network.0.floating_ip": "",
                            "network.0.mac": "fa:16:3e:2f:1b:ab",
                            "network.0.name": "services",
                            "network.0.port": "",
                            "network.0.uuid": "e8160f83-f286-4c1a-896e-aebd905126d0",
                            "region": "RegionOne",
                            "security_groups.#": "4",
                            <..>
                            "stop_before_destroy": "false"
                        },
```

### Steps to Reproduce
1. Change openstack_networking_network_v2.this.name to something different (e.g. add _2)
2. Run `terraform apply`. There will be only one change in the network name
3. Run `terraform apply` again. It will suggest to recreate compute instance.

**Comment by jtopjian** [comment]
Unfortunately I don't think there's anything we can do about this behavior except maybe document it.

Specifying a network by name was an early convenience feature. If we were to ignore "Force New" on a network name change, then it would be a serious backwards breakage. I totally understand that in some cases, even though the network name has changed, it's still the same network.

Years after we implemented the ability to specify a network by name, this Terraform provider is now quite robust. A network could/should always be specified by a UUID. If you don't know the UUID of the network off-hand, then it's possible to obtain this by using the `openstack_networking_network_v2` data source.

@ozerovandrei this is something we'll want to keep in mind for the future "server" resource: only support UUIDs of attributes and not names.

**Comment by kayrus** [comment]
In theory `ComputedWhen` option can help. Unfortunately it's functionality is not implemented:
https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L164..L169
https://github.com/hashicorp/terraform/issues/1436

**Comment by alexanderbystrom** [comment]
This issue is still relevent today, let's say I do change the network name and want to get back to the state before. Even after changing the name of the network back. Terraform still wants to recreate the instances.

**Comment by m0ter** [comment]
This issue is still relevent today, let's say I do change the network name and want to get back to the state before. Even after changing the name of the network back. Terraform still wants to recreate the instances.
